// app/layout.tsx
import type { Metadata } from 'next';
import { ReactNode } from 'react';
import { Navbar } from '@/components/layout/navbar';
import './globals.css';
import Providers from './providers';

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: ReactNode }) {
    return (
        <html lang="en">
        <head>
            <link rel="preconnect" href="https://rsms.me/" />
            <link rel="stylesheet" href="https://rsms.me/inter/inter.css" />
        </head>
        <body className="bg-neutral-50 text-black dark:bg-neutral-900 dark:text-white">
        <Providers>
            <Navbar />
            <main>{children}</main>
        </Providers>
        </body>
        </html>
    );
}
