import type { Metadata } from "next";
import { cookies } from 'next/headers';
import { ReactNode } from 'react';
import { CartProvider } from "@/components/cart/cart-context";
import { getCart } from "@/lib/shop";
import { Navbar } from "@/components/layout/navbar";
import "./globals.css";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({ children }: { children: ReactNode }) {
    const cartId = (await cookies()).get('cartId')?.value;
    const cart = getCart(cartId);

    return (
        <html lang="en">
            <head>
                <link rel="preconnect" href="https://rsms.me/" />
                <link rel="stylesheet" href="https://rsms.me/inter/inter.css" />
            </head>
            <body className="bg-neutral-50 text-black dark:bg-neutral-900 dark:text-white">
                <CartProvider cartPromise={cart}>
                    <Navbar />
                    <main>{children}</main>
                </CartProvider>
            </body>
        </html>
    );
}
